version: '1.0'
name: release
displayName: release
triggers:
  trigger: auto
  push:
    tags:
      prefix:
        - ''
stages:
  - name: stage-58a6d5eb
    displayName: build
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: execute@docker
        name: execute_by_docker
        displayName: 基于镜像的脚本执行
        certificate: ''
        image: hub.atomgit.com/amd64/ubuntu:22.04
        command:
          - 'apt-get update                                                       '
          - 'apt-get install -y build-essential curl cmake openssl libssl-dev git '
          - 'git submodule update --init --recursive --depth=1                    '
          - 'cd src                                                               '
          - ./release.sh
          - 'cp ./cppnet.tar.gz ../cppnet-ubuntu-release.tar.gz         '
          - 'cp ./cppnet-ssl.tar.gz ../cppnet-ubuntu-ssl-release.tar.gz '
        artifacts:
          - name: BUILD_ARTIFACT
            path:
              - ./cppnet-ubuntu-release.tar.gz
              - ./cppnet-ubuntu-ssl-release.tar.gz
        notify: []
        strategy:
          retry: '0'
  - name: stage-56a39974
    displayName: release_upload
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: publish@general_artifacts
        name: publish_general_artifacts
        displayName: 上传制品
        dependArtifact: BUILD_ARTIFACT
        artifactName: output
        notify: []
        strategy:
          retry: '0'
  - name: stage-7b9fe2d3
    displayName: release
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: publish@release_artifacts
        name: publish_release_artifacts
        displayName: 发布
        dependArtifact: output
        version: 1.0.0.0
        autoIncrement: true
        notify: []
        strategy:
          retry: '0'

