version: '1.0'
name: test
displayName: test
triggers:
  trigger: auto
  push:
    branches:
      prefix:
        - master
stages:
  - name: stage-688a396e
    displayName: test
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: execute@docker
        name: execute_by_docker
        displayName: build_and_test
        certificate: ''
        image: hub.atomgit.com/amd64/ubuntu:22.04
        command:
          - apt-get update
          - apt-get install -y build-essential curl cmake openssl libssl-dev git
          - git submodule update --init --recursive --depth=1
          - cd src
          - ./build.sh
          - ./bin/test_bin
        notify:
          - certificate: 5989d7b0-88ba-013d-2c17-6ac3c133bbed
            events:
              - fail
            content:
              - repository
              - pipeline
              - stage
              - task
              - operator
              - branch
              - detail
            type: feishu
        strategy:
          retry: '0'
          timeout: 10
          expression: []
