name: docs_page
on:
  push: #设置触发规则
    branches:
      - main
      - master
    paths:
      - 'docs/**'
      - '.github/workflows/docs.yml'
      - 'README.md'
      - 'README.en.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code #这部分是为了从github自动clone代码
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Number of commits to fetch. 0 indicates all history for all branches and tags.Default: 1
          submodules: true
      - name: Run Build Assert #需要执行的命令
        run: |
          cd ./docs
          ./update.sh
          rm -rf ./obsidian2web
          mv ./cppnet/README.md Home.md
          mv ./cppnet/README.en.md .
          cd ..
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./book

      - name: Wiki Update
        uses: spenserblack/actions-wiki@v0.3.0
        with:
          # Whatever directory you choose will be mirrored to the GitHub
          # .wiki.git. The default is .github/wiki.
          path: docs

  # Deploy job
  deploy:
    # Add a dependency to the build job
    needs: build
    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 # or specific "vX.X.X" version tag for this action
